### ISSUE TITLE
D2SE version string issue

### ISSUE THREAD

**Issue by Gecko94** [IAmTrial/SlashGaming-Diablo-II-API#280]
I'm using the latest build of SGD2FreeRes standalone version. It seems to work flawless - Amazing work
Thank You!

I've tried all kinds of ways to get SGD2FreeRes working in D2GS. Here are a few and these are the errors I get.

**1) Load from PlugY.ini**
![Error_LaunchedFromD2SEPlugY14](https://user-images.githubusercontent.com/85077147/120117335-f90bb700-c149-11eb-9a38-fc78425e4c7b.jpg)

Version string in D2SE_Setup.ini
D2Core=1.13c

**2) Load from D2SE_Setup.ini**
ModAllowPlugY=1
ModDll2=SGD2FreeRes.dll

Tried loading with and without ModMPQ3=SGD2FreeRes.mpq
no config file generated - no error on screen

**3) Rename SGD2FreeRes.dll to PlugY.dll to load it that way..**
![Error_LaunchedFromD2SERenamedToPlug_dll](https://user-images.githubusercontent.com/85077147/120117429-6fa8b480-c14a-11eb-856d-01c66ad1e372.jpg)

**Comment by IAmTrial** [comment]
Just so the both of us understand each other, are you referring to D2GS as in Diablo II Game Server?

If so, I've not tested any of the code I've written for SGD2MAPI to run on D2GS because I have not used SGD2MAPI to write anything that would meaningfully affect the server code. In this case, the injection of SGD2FreeRes into the server code would serve no purpose, as SGD2FreeRes works entirely client-sided. So to use D2SE to load SGD2FreeRes into a server doesn't make much sense. Until further clarification is provided, I will simply address the issue of the version string and D2SE issue.

As for your concerns regarding D2SE versions string errors, I will double check whether there is an issue on SGD2MAPI's side.

**Comment by Gecko94** [comment]
Sorry its a typo.. I meant in D2SE  - as standalone installation single player.

I can't understand your code, so sorry if I'm way off, but maybe its expecting D2SE to parse a unicode version string from D2SE_Install.txt and but the file itself is stored as ANSI.

https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-API/blob/develop/SlashGaming-Diablo-II-API/src/cxx/backend/d2se/d2se_game_version.cc

static constexpr ::std::array<
    VersionStringTableEntry,
    8
> kVersionStringTable = {{
    { L"1.07", ::d2::GameVersion::k1_07 },
    { L"1.08", ::d2::GameVersion::k1_08 },
    { L"1.09b", ::d2::GameVersion::k1_09B },
    { L"1.09d", ::d2::GameVersion::k1_09D },
    { L"1.10f", ::d2::GameVersion::k1_10 },
    { L"1.11b", ::d2::GameVersion::k1_11B },
    { L"1.12a", ::d2::GameVersion::k1_12A },
    { L"1.13c", ::d2::GameVersion::k1_13C }
}};

**Comment by Gecko94** [comment]
Sorry its a typo.. I meant D2SE - as standalone installation single player.

I can't understand your code, so sorry if I'm way off, but maybe its expecting to parse a unicode version string from D2SE_Install.ini, but the file itself is stored as ANSI.

https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-API/blob/develop/SlashGaming-Diablo-II-API/src/cxx/backend/d2se/d2se_game_version.cc

static constexpr ::std::array<
VersionStringTableEntry,
8

    kVersionStringTable = {{
    { L"1.07", ::d2::GameVersion::k1_07 },
    { L"1.08", ::d2::GameVersion::k1_08 },
    { L"1.09b", ::d2::GameVersion::k1_09B },
    { L"1.09d", ::d2::GameVersion::k1_09D },
    { L"1.10f", ::d2::GameVersion::k1_10 },
    { L"1.11b", ::d2::GameVersion::k1_11B },
    { L"1.12a", ::d2::GameVersion::k1_12A },
    { L"1.13c", ::d2::GameVersion::k1_13C }
    }};

**Comment by IAmTrial** [comment]
The file text may be encoded with ANSI 7-bit, but all Windows functions used are the "W" variant. This means that the INI will be converted to wide characters when read in. You can see in the error message that the string is indeed being read in correctly.

The main problem that the error is showing is that the version table was unable to locate a version that corresponds to that string. The string is supposed to be valid, so perhaps there is something wrong with the table search. Looking at the code, I don't see anything that would particularly cause the search to fail with the string that is provided.

Could you post a screenshot of the `Properties -> Details` tab of the SGD2FreeRes.dll file you are using? I tried to replicate your issue but was unable to get any results. I also use the first method to load the DLL file.

**Comment by Gecko94** [comment]
![SGD2FreeRes](https://user-images.githubusercontent.com/85077147/120271089-e7b8cc80-c267-11eb-8c48-5ac132b75563.jpg)

**Comment by Gecko94** [comment]
![D2SE_Compatiblity](https://user-images.githubusercontent.com/85077147/120276341-cc51bf80-c26f-11eb-8cb9-ce57a6b9d640.jpg)

**Comment by Gecko94** [comment]
Checking Back to Hellfire mod for D2SE in D2 v1.10 with PlugY v11 install.

![Error_LaunchedFromD2SEPlugY11](https://user-images.githubusercontent.com/85077147/120283360-54d45e00-c278-11eb-9923-bb87acd74457.jpg)

**Comment by IAmTrial** [comment]
I would have to guess that the D2SE -> version table searching code is not behaving as it should. I'll spend some time reviewing it and will let you know what I find.

**Comment by IAmTrial** [comment]
I've identified a possible cause of this particular bug. On lines 128-133, the string is converted to lowercase characters and stored in the array defined at line 126. The problem is that `std::transform` does not set a null-terminator at the end of the lower-cased string. This is because the `cend()` iterator does not include the null-terminator. As you can see, `std::transform` is called, and then `std::equal_range` is called. This does not guarantee that the lower-case string will be null-terminated.

https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-API/blob/fc18a9d8c30528ac45cea3240af4736e7aef7c10/SlashGaming-Diablo-II-API/src/cxx/backend/d2se/d2se_game_version.cc#L123-L141

**Comment by Gecko94** [comment]
Interesting.. I'm not familiar enough with this style of coding and the std functions to know where to find possible issues. Thanks for the explanation.

**Comment by IAmTrial** [comment]
I have released a new version of SGD2FreeRes. Hopefully this new version has resolved your issue. If not, I will investigate this issue further.

https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution/releases/tag/3.0.2.1

If no response is provided within a week, I will close the issue.

**Comment by Gecko94** [comment]
I'm happy to say the issue is fixed.  Not sure if issue related to Win8.1, but that is what I was testing in. 

**Tested in D2SE v 2.2.20  with latest SGD2FreeRes Vanilla - 1068x600:**

Load from PlugY 14  - no issues.
Load from BaseMod 1.13.6 - no issues.

both tested in 
DDraw in windowed mode. 
Glide3x full screen

**Tested with latest SGD2FreeRes Vanilla in Standalone - 1068x600:**

Load from PlugY 14  - no issues.
Load from BaseMod 1.13.6 - no issues.

Thank you for creating this masterpiece of coding!
